name: Poster Upload

on: 
  push:

jobs:
  show-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display success message
        run: echo "Poster Uploaded Successfully"
